### ISSUE TITLE
curl -A ''  -v https://serholiu.com 500错误

### ISSUE THREAD

**Issue by ultimate010** [SerhoLiu/serholiu.com#7]
我很早以前fork的版本，发现里面有500错误，因为当代理爬虫爬到的时候，没有传user-agent会出错。
现在新的好像改了，但是测试还有500错误，不知是哪儿有问题？
self._context.is_mobile = is_mobile(self.request.headers.get('User-Agent', ''))

**Comment by SerhoLiu** [comment]
@ultimate010 改成你写的那样应该就不会有问题了，我的博客之所以有问题，是因为我的代码还没改。。。
